export default {
  REQUEST_GOOGLE_AUTH: 'REQUEST_GOOGLE_AUTH',
  RECEIVE_GOOGLE_AUTH: 'RECEIVE_GOOGLE_AUTH',
  FAILED_GOOGLE_AUTH: 'FAILED_GOOGLE_AUTH',
  REQUEST_GET_BOXES: 'REQUEST_GET_BOXES',
  RECEIVE_GET_BOXES: 'RECEIVE_GET_BOXES',
  FAILED_GET_BOXES: 'FAILED_GET_BOXES',
  SELECT_BOX: 'SELECT_BOX'
};
