export default {
  REQUEST_GOOGLE_AUTH: 'REQUEST_GOOGLE_AUTH',
  RECEIVE_GOOGLE_AUTH: 'RECEIVE_GOOGLE_AUTH',
  FAILED_GOOGLE_AUTH: 'FAILED_GOOGLE_AUTH',

  REQUEST_GET_BOXES: 'REQUEST_GET_BOXES',
  RECEIVE_GET_BOXES: 'RECEIVE_GET_BOXES',
  FAILED_GET_BOXES: 'FAILED_GET_BOXES',

  REQUEST_UPDATE_BOX: 'REQUEST_UPDATE_BOX',
  RECEIVE_UPDATE_BOX: 'RECEIVE_UPDATE_BOX',
  FAILED_UPDATE_BOX: 'FAILED_UPDATE_BOX',

  SELECT_BOX: 'SELECT_BOX',

  SIGNOUT: 'SIGNOUT',
};
